name: Generate Stats Images

on:
  schedule:
    - cron: "5 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maurodesouza/profile-readme-stats@master
        with:
          username: DiTulio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
